### ISSUE TITLE
App werkt niet meer

### ISSUE THREAD

**Issue by br600** [gruijter/com.gruijter.sms#10]
Hi Robin, allereerst complimenten voor de mooie app die bij mij al een jaar foutloos draait. Helaas doet hij het afgelopen dagen niet meer. Ik heb niets veranderd en krijg de volgende melding. App ook opnieuw geinstalleerd maar dezelfde fout blijft bestaan.

Error: Error: 401: {"errors":[{"code":2,"description":"Request not allowed (incorrect access_key)","parameter":"access_key"}]}

Provider is Messagebird. App heeft het altijd goed gedaan met de settings.

Alvast bedankt.

Groeten,
Erik

**Comment by gruijter** [comment]
Hi Erik,

I will investigate.

Thx for reporting and for your compliments!

**Comment by gruijter** [comment]
Found it. I did a faulty search and replace in v3.0.1. So actually multiple services were affected.  This is fixed in 3.0.2 (already published in the store)
