### ISSUE TITLE
sms naar service nummer

### ISSUE THREAD

**Issue by br600** [gruijter/com.gruijter.sms#11]
Hi Robin,

Allereerst complimenten en bedankje voor je top app.
Ik wil graag een sms naar een servicenummer sturen (4111 Parkmobile) om een parkeeractie te starten. 
Nu komen die sms'n niet door en komt er een foutmelding. Nu weet ik niet of het door de app komt of door de provider (messagebird). Ik ben bang dat het door de provider komt. Klopt dat?
Weet jij toevallig anders een provider of manier om wel naar een servicenummer te sms'n?

Groeten,
Erik

**Comment by gruijter** [comment]
Hi Erik,

Ik denk dat alle providers daar een probleem mee hebben. Het is een NL servicenummer en de providers werken internationaal. Heb je al geprobeerd met +314111 ?

**Comment by br600** [comment]
Hi Robin,

+31 had ik inderdaad ook al geprobeerd en werkt helaas ook niet.
Ik ben dan bang dat het voorlopig niet gaat lukken.

Bedankt iig.

Groeten,
Erik

Op do 20 mei 2021 om 20:04 schreef gruijter ***@***.***>:
