### ISSUE TITLE
46elks.se

### ISSUE THREAD

**Issue by migoman958** [gruijter/com.gruijter.sms#12]
Can't get elk46.se to work. 
Error: Error: 401: API access requires Basic HTTP authentication. Read documentation or examples. 

app version 3.0.2

**Comment by gruijter** [comment]
I just checked but it works.
Make sure you use the API credentials to login (so not the web login)

**Comment by migoman958** [comment]
Thank you. I found what's wrong. Because elk46.se is the first in the list and you don't select anything - there is both user-id and api-id - fields. Using them makes the error.
I did reinstall the app - selecting another and then selecting elk46.se. Now it works fine.........

**Comment by gruijter** [comment]
Ah ok. That is a small bug then. Good it is working for you.

**Comment by gruijter** [comment]
fixed in 3.0.3
