### ISSUE TITLE
Add provider

### ISSUE THREAD

**Issue by mcrbrauers** [gruijter/com.gruijter.sms#16]
can you please add a API-based sms provider:

Cheapconnect.net

POST URL | https://account.cheapconnect.net/API/v1/sms/SendSMS/
-- | --
(string) Jouw API key is: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
(e164 of tekst) Afzender alfanumeriek (maximaal 11 karakter) of numeriek (maximaal 11 cijfers in E164 formaat)
(e164) Ontvanger in E164 formaat zonder +, voorbeeld 3161234567
(string) Bericht naar de afzender

Thank you!

**Comment by gruijter** [comment]
I can look into it. I have created an account but need testing credit. Can you arrange that for me? My account is gruijter@hotmail.com.
Or otherwise I can send you a 'tikkie' for 5 euro.

**Comment by mcrbrauers** [comment]
Thanks for looking into it.You can send me a tikkie..The other option is not working for me.
-------- Oorspronkelijk bericht --------Van: gruijter ***@***.***> Datum: 04-02-2022  10:29  (GMT+01:00) Aan: "gruijter/com.gruijter.sms" ***@***.***> Cc: mcrbrauers ***@***.***>, Author ***@***.***> Onderwerp: Re: [gruijter/com.gruijter.sms] Add provider (Issue #16) 
I can look into it. I have created an account but need testing credit. Can you arrange that for me? My account is ***@***.***
Or otherwise I can send you a 'tikkie' for 5 euro.

**Comment by gruijter** [comment]
Can you transfer it to my paypal account?

https://paypal.me/gruijter

Use 'transfer money to a friend' otherwise Paypal will charge costs

**Comment by mcrbrauers** [comment]
Beste Robin,Ik heb 5euro overgemaakt naar je paypal account..Alvast bedankt!Groet,Marcel Brauers
-------- Oorspronkelijk bericht --------Van: gruijter ***@***.***> Datum: 05-02-2022  21:35  (GMT+01:00) Aan: "gruijter/com.gruijter.sms" ***@***.***> Cc: mcrbrauers ***@***.***>, Author ***@***.***> Onderwerp: Re: [gruijter/com.gruijter.sms] Add provider (Issue #16) 
Can you transfer it to my paypal account?
https://paypal.me/gruijter
Use 'transfer money to a friend' otherwise Paypal will charge costs

**Comment by gruijter** [comment]
New version 3.1.0 is published in the app store. Please test it and let us know in the forum if it works well :)

https://community.homey.app/t/app-send-sms/3025/108
