### ISSUE TITLE
smsgateway.me

### ISSUE THREAD

**Issue by gajdur** [gruijter/com.gruijter.sms#2]
Using smsgateway.me is giving this error message back: `error 503 <html><head><title`

**Comment by Richaars** [comment]
I had the same problem with smsgateway.me (error 503)

Log:

2018-08-14 21:51:02 [log] [SendSMSApp] Error: error: 503 
2018-08-14 21:51:01 [log] [SendSMSApp] smsgateway.me to 0614429808: Hallo 
2018-08-14 21:46:46 [log] [SendSMSApp] Error: error: 503 
2018-08-14 21:46:46 [log] [SendSMSApp] smsgateway.me to 0614429808: Hallo 
2018-08-14 21:46:42 [log] [SendSMSApp] Error: error: 503 
2018-08-14 21:46:42 [log] [SendSMSApp] smsgateway.me to 0614429808: Hallo 
2018-08-14 21:45:38 [err] [SendSMSApp] error reading logfile: ENOENT: no such file or directory, open '/userdata/log.json' 
2018-08-14 21:45:38 [log] [SendSMSApp] capturing stderr 

Any news?

**Comment by Richaars** [comment]
Hi Gruijter,

Thanks for the quick reply.

Great news that you are awera of the problem and able to fix it!

Thank you in advance.

With kind regards,

Richard

Op 14 aug. 2018 22:21 schreef gruijter <notifications@github.com>:

Hi Both,

thx for reporting this. 503 means the smsGateway.me web service is unavailable.

I checked, and It seems that they recently changed their web address for the api. I will fix it in a next version app when I find some spare time.

**Comment by gruijter** [comment]
I just uploaded new version 2.0.1 to the appstore, and it is pending approval by Athom. You can also install from GitHub if you can't wait. Please let me know if this fixes it, I was unable to test myself yet.

**Comment by Richaars** [comment]
I installed the new version, theres a new error message:

error: 400 {"status":"fail","message":"Could not process request","data":{"exception":"Unknown Error"}}

**Comment by gruijter** [comment]
Mmh, I have to dig deeper then. Weird how they just chsnge the api without out even notifying users. And my testaccount is somehow blocked, so I need to setup a new account. They are not making things easy....

**Comment by gruijter** [comment]
OK, had to fully rewrite this service. It uses an API token now in stead of username/password. On my phone I had to manually push the çheck server now' button to start sending the sms... I'm not sure if smsgateway.me is such a nice service anymore :(

Anyway, you are good to go with this update 👍

**Comment by gajdur** [comment]
Hi @gruijter and thx for fixing smsgateway. Unfortunaly i receive now this error:
`
2018-08-20 06:55:37 [log] [SendSMSApp] Error: error: 400 {"status":"fail","message":"Could not process request","data":{"exception":"Unknown Error"}} at Promise (/app.js:343:20) at at process._tickCallback (internal/process/next_tick.js:188:7) `

**Comment by gajdur** [comment]
Sorry, my mistake, my API Token was wrong  and received another error message. Now is working even without opening the sms app on my S8.

**Comment by gruijter** [comment]
Cool! Thx for letting me know that it works 😀

**Comment by gajdur** [comment]
Hi @gruijter , sorry to bother you. Something is wrong again:
`2018-09-18 14:17:09 [log] [SendSMSApp] Error: error: 400 {"status":"fail","message":"Could not process request","data":{"exception":"Invalid input"}} at Promise (/app.js:343:20) at at process._tickCallback (internal/process/next_tick.js:188:7) 
2018-09-18 14:17:09 [log] [SendSMSApp] smsgateway.me to +41760000000: test sms `

Tnx
Gajdur

**Comment by gruijter** [comment]
Hi gajdur,

Sorry for the late reply. Extremely busy with my paying job 😓. When I find time I will look into it, but please dont hold your breath.

**Comment by Albert1085** [comment]
Hey Robin,

first of all I would like to thank you for your both simple and reliable application to integrate the forwarding of SMS in Homey. That's even nowadays very useful regarding to worse mobile internet connections, when therefore _push notifications_ can't be received in the very next moment a flow was started or a status is changed.
Beside of this, Homey itself doesn't cache actually push notifications as long as the owner's respectively the user's mobile phone isn't online. This means, in the end, such messages are only delivered, if your device is connected with the internet, when the push notification was issued. 
So, I'm happy to send as well SMS as an alternative message option. :-D

This is why I'm still interested in using preferably my own mobile phone provider. It's called OTELO, a brand of Vodafone Germany. Do you think, it's usable with your app? But I only new the SMS-Service central number: +49 172 227 03 33. Neither the API ID nor a username and passwort.
How Do you see this matter?
Thanks for your reply!

Kind regards
Albert

**Comment by gruijter** [comment]
Hi Albert,

glad you like the app!

Concerning using your own phone: Homey can not send directly to an SMS-service centre. It always needs to go through a intermediate provider. There used to be an app that you could install on your phone that enabled sending an SMS via your phone as a gateway. This app (smsGate) stopped working unfortunately.

If you can find a similar app that makes your phone act as a gateway I would be glad to look into that.
