### ISSUE TITLE
Hi @gruijter , sorry to bother you. Something is wrong again:

### ISSUE THREAD

**Issue by gajdur** [gruijter/com.gruijter.sms#3]
`2018-09-18 14:17:09 [log] [SendSMSApp] Error: error: 400 {"status":"fail","message":"Could not process request","data":{"exception":"Invalid input"}} at Promise (/app.js:343:20) at at process._tickCallback (internal/process/next_tick.js:188:7) 
2018-09-18 14:17:09 [log] [SendSMSApp] smsgateway.me to +41760000000: test sms `

Tnx
Gajdur

_Originally posted by @gajdur in https://github.com/gruijter/com.gruijter.sms/issues/2#issuecomment-422369642_

**Comment by gajdur** [comment]
Hi @gruijter  and thank you. Do not stress yourself, i'm using email and homey app notification atm.

**Comment by gruijter** [comment]
No stresd 😎🤘
