### ISSUE TITLE
Some help to use your app would be grate

### ISSUE THREAD

**Issue by johanstockholm** [gruijter/com.gruijter.sms#4]
Sorry but I'm new to homey so some things art that clear to me. 

To configure I need some strings. Where do i find them?  Some short tutorial would be nice.

Api ID/handle ? 
Username  ?
Password/id  ?
From number ?

Thanks for that I think is a grate App!

**Comment by gruijter** [comment]
To send an SMS you need an account with one of the SMS services that the app supports. In the settings page, select a service, and klick on the weblink to get more information on that service.

To compare a number of providers for their SMS rates, you can use this site: http://www.voip-comparison.com/

Unfortunately the ‘free’ service that uses your own mobile as gateway (smsGateway.me) is not operational at the moment. If you know any other gateway that you would like to have integrated, preferably one that uses your own mobile, please let me know :slight_smile:
