### ISSUE TITLE
Error 401 for 46Elks

### ISSUE THREAD

**Issue by Peters2000** [gruijter/com.gruijter.sms#7]
Hi,

I can't get 46Elks to work. I filled out my username and password. Did not fill out API ID; this field is disabled. Sending a test message results in "_Error: 401: API access requires Basic HTTP authentication._" I already sent a Diagnostics report.

If you can recommend another provider than that's ok as well.

**Comment by gruijter** [comment]
Thx 4 reporting. I will investigate!

**Comment by gruijter** [comment]
My test account with them is not working anymore, so cannot debug 46elks at the moment. I have asked them to re-open my account.

On your second question: I dont have a recommendation for any of the providers. You can use any you like :)

**Comment by gruijter** [comment]
I created v 2.2.3 and was able to test it without an issue. It will be released soon in the appstore.

When you enter credentials make sure to fill in the correct api_username (long code), and the api_password (another long code)

**Comment by Peters2000** [comment]
Thanks for your efforts. I am now getting this error: "403: Alphanumeric numbers may not start with a digit".

I am not sure what number it is referring to. The password started with a number so I recycled it until I had one starting with a letter. It made no difference. I also tried the phone number starting with 0031 instead of +31, but no difference then either.

**Comment by gruijter** [comment]
What did you enter in the 'from' field? When testing I used `gruijter` in the from field, and `+31...` in the 'to' field, and some words in the 'message' field.

**Comment by Peters2000** [comment]
The from field had the value "46Elks" by default. I now replaced that with my cell phone number, and it works now! So "to" and "from" are equal now.

Thanks for your help!

Arno

On Wed, Oct 9, 2019, at 08:47, gruijter wrote:

What did you enter in the 'from' field? When testing I used gruijter in the from field, and +31... in the 'to' field, and some words in the 'message' field.

**Comment by gruijter** [comment]
Ah, super. Have phun texting!
