### ISSUE TITLE
Support for gatewayapi.com (sic.)

### ISSUE THREAD

**Issue by ralftar** [gruijter/com.gruijter.sms#9]
Would be great if you could ads support for using https://gatewayapi.com/ as sending service (yes: they have a stupid name).

**Comment by gruijter** [comment]
I can give it a try. Is there a free way for me to test it during development, or do I need credit?

**Comment by ralftar** [comment]
Just create a free account, and request free cerdits from support:

> If you would like to try GatewayAPI.com before you get started, you can write to us on the live support chat and request free test credit.

Let me know if there are any hassle and we can figure other options.

**Comment by gruijter** [comment]
@ralftar any feedback for me?

**Comment by ralftar** [comment]
@gruijter will run a test and report back. Thanks!

**Comment by ralftar** [comment]
@gruijter is it listed under a different name? I was not able to find it in the list. Or perhaps the test version is unavailable now?

**Comment by gruijter** [comment]
You couldnt find the app or couldnt find the provider in the app?

App is stable release now (3.0.1)
Provider is Gatewayapi

**Comment by ralftar** [comment]
Cannot find Gatewayapi in 3.0.1's provider list. Makes me wonder if i'm using the right version (was not able to find the test-version anymore).

**Comment by gruijter** [comment]
V 3.0.1 is the correct version. It is right there between CM Direct an Free Mobile.....

**Comment by gruijter** [comment]
Super!
(it should have been alphabetically by the way LOL)
